version: '3'
services:
  anaconda:
    image: continuumio/miniconda3:latest
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: > 
       bash -c "echo 'Iniciando Projeto'
       && apt update 
       && yes | apt upgrade 
       && yes | apt install default-jdk -y
       && yes | conda install conda-forge::ipykernel
       && yes | conda install conda-forge::pyspark
       && yes | conda install conda-forge::unidecode
       && yes | apt install unzip
       && yes | apt install p7zip-full
       && yes | apt install coreutils
       && yes | conda install conda-forge::matplotlib
       && tail -f /dev/null"
